### ISSUE TITLE
Non-size attributes should not change the size of elements.

### ISSUE THREAD

**Issue by gpellis** [hoplon/ui#28]
Adding `:av :beg` to an element can cause the size of it's children to change.

Here is a minimal example.

```
(defelem color-stack
  [attributes children]
  (vector
   (elem :sh (r 1 1)
         :sv 52
         :c :green)
   (elem :sh (r 1 1)
         :sv (- (r 1 1) 104)
         :c :lightblue
         "This should take up most of the screen.")
   (elem :sh (r 1 1)
         :sv 52
         :c :green)))

(defelem align-vertical-bug-demo
  [attributes children]
  (elem :sh (r 1 1)
        :sv (r 1 1)
        (elem :sh (r 1 2)
              :sv (r 1 1)
              (color-stack))
        (elem :sh (r 1 2)
              :sv (r 1 1)
              :av :beg
              (color-stack))))

(window
 :title "Align Vertical Bug Demo"
 (elem :s 500
       (allign-vertical-bug-demo)))
```

**Comment by jumblerg** [comment]
this bug is a subset of issue #25. the problem specifically demonstrated by this example has been resolved in narrow terms, but the larger problem of vertically centering content within an element set to a percentage/ratio height remains. 

![screen shot 2016-12-06 at 23 18 13](https://cloud.githubusercontent.com/assets/169224/20954556/55cda3ee-bc0a-11e6-9d8e-53ff913fc8bf.png)
